### PR TITLE
refactor(input-text): use ElementInternals

### PR DESCRIPTION
**Pull request by eriklharper**
**Related Issue:** #8126

## Summary

This PR updates `input-text` to use `ElementInternals` for native form support, replacing the `HiddenFormInputSlot` usage.  It also introduces a new `useForm` controller that integrates with `ElementInternals` that form components can utilize.

### Noteworthy changes

* introduces
  * `useForm` controller to manage form association
  * `form-associated.ts` browser mode common test helper
  * interface for common test setup
* enables validation in `input-text` form association tests, which previously were not enabled
* avoids porting tests related to
  * the previous implementation (for example relying on the hidden form input), which are no longer needed in browser tests
  * browser validation focus, since this is handled by the `ElementInternals` implementation and does not require additional coverage
* refactors input utilities to reuse input syncing used by the input delegate for validation
* [side effect] caret behavior now matches native inputs more closely: when focusing with an initial value the caret stays at the start, and after the value changes focusing places the caret at the end

### CODE REVIEW

File: packages/components/src/components/input-date-picker/input-date-picker.e2e.ts [hunk 1]
```diff
@@ -224,13 +224,14 @@ it("should clear active date properly when deleted and committed via keyboard",
   await page.waitForChanges();
 
   for (let i = 0; i < 10; i++) {
-    await input.press("Backspace");
+    await input.press("Delete");
```
Comment (eriklharper) [inline packages/components/src/components/input-date-picker/input-date-picker.e2e.ts:227]: Not sure why, but this change allowed this test to pass locally for me.  Haven't tested to see if in CI this makes a difference or not.

File: packages/components/src/controllers/useForm.ts [hunk 2]
```diff
@@ -0,0 +1,356 @@
...
+ * messages that are set by the browser will be cleared. If a user sets
+ * validationMessage to a custom value, they are responsible for clearing it.
+ *
+ * Exported for testing purposes.
+ *
+ * @param componentTag the tag of the component, e.g. "calcite-input"
+ * @returns the event name
+ */
+export function getClearValidationEventName(componentTag: string): string {
+  const componentTagCamelCase = componentTag
```
Comment (maxpatiiuk) [inline packages/components/src/controllers/useForm.ts]: nit: there is kebabToPascal + uncapitalize in @arcgis/toolkit that does the same

File: packages/components/src/controllers/useForm.ts [hunk 3]
```diff
@@ -0,0 +1,356 @@
...
+ *
+ * Allows calling submit/reset methods on the form.
+ */
+interface FormOwner extends LitElement {
+  /**
+   * The ID of the form to associate with the component.
+   *
+   * When not set, the component will be associated with its ancestor form element, if any.
+   *
+   * Note that this prop should use the `@Prop` decorator.
```
Comment (maxpatiiuk) [inline packages/components/src/controllers/useForm.ts]:
```suggestion
   * Note that this prop should use the `@property` decorator.
```

File: packages/components/src/controllers/useForm.ts [hunk 4]
```diff
@@ -0,0 +1,356 @@
...
+          if ("validationMessage" in component && component.validationMessage === validationMsg) {
+            component.validationMessage = "";
+          }
+        },
+        { once: true },
+      );
+    }
+
+    controller.onConnected(() => {
+      // workaround for luminaFormAssociatedCallback not firing
```
Comment (maxpatiiuk) [inline packages/components/src/controllers/useForm.ts]: can you provide more details?
is this a Lumina bug, or a browser behavior?

File: packages/components/src/controllers/useForm.ts [hunk 5]
```diff
@@ -0,0 +1,356 @@
...
+
+  /** For boolean-valued components, this property defines whether the associated value is submitted to the form or not. */
+  checked?: boolean;
+
+  /**
+   * The initial checked value for this form component.
+   *
+   * When the form is reset, the checked property will be set to this value.
+   */
+  defaultChecked?: boolean;
```
Comment (maxpatiiuk) [inline packages/components/src/controllers/useForm.ts]: hmm, I can see how willUpdate's typing makes this a bit trickier.

if you wish to avoiding duplicating the props, this is one option:

- remove the checked and defaultChecked props from here, replacing them with extending CheckableFormProps:

```ts
interface FormComponent<T = any> extends FormOwner, CheckableFormProps, LitElement {
```

- then, create these interfaces instead of CheckbableFormComponent:

```ts
interface CheckableFormComponent<T = any> extends FormComponent<T>, CheckableFormProps {}
interface CheckableFormProps {
  checked: boolean;
  defaultChecked: boolean;
}
```

**Review by maxpatiiuk — APPROVED** [review]

**Review by jcfranco — APPROVED** [review]

File: packages/components/src/controllers/useForm.ts (hunk 4 above)
Comment (jcfranco) [reply packages/components/src/controllers/useForm.ts]: This was added prior to the Lumina fix to keep integration moving forward.

File: packages/components/src/controllers/useForm.ts (hunk 5 above)
Comment (jcfranco) [reply packages/components/src/controllers/useForm.ts]: Thanks for the suggestion. I ended up doing a `Partial` + `Pick` as the above seems to break
`isCheckable` and causes the type to resolve to `never`:

```tsx
function getFormValue(): any {
  // ...
  return component.value; // TS2339: Property value does not exist on type neve
}
```

File: packages/components/src/components/input-date-picker/input-date-picker.e2e.ts (hunk 1 above)
Comment (jcfranco) [reply packages/components/src/components/input-date-picker/input-date-picker.e2e.ts:227]: The caret position seems to have been affected. It was previously set at the end of the value and now it's set at the start. Let's dig a bit to see what's causing this. ⛏️

Comment (jcfranco) [reply packages/components/src/components/input-date-picker/input-date-picker.e2e.ts:227]: It looks like the change was introduced in 687e2110e541796e7dac4833e7eaf805cf2ca50a (change from `onUpdated` to `onUpdate`).

After a [quick comparison with `<input>`](https://codepen.io/jcfranco/pen/GgjjyXa), it appears that the caret is only affected when there is a runtime change. With the current changes, the behavior matches native better. If you do the same (set the value programmatically before focusing), the caret moves. From that perspective, this appears to be an improvement.

File: packages/components/src/components/input-date-picker/input-date-picker.e2e.ts [hunk 6]
```diff
@@ -224,7 +224,7 @@ it("should clear active date properly when deleted and committed via keyboard",
...
```
[the remark this answers is not in the document]
Comment (jcfranco) [reply packages/components/src/components/input-date-picker/input-date-picker.e2e.ts:227]: This is explained [here](https://github.com/Esri/calcite-design-system/pull/13985#discussion_r2907520434).

File: packages/components/src/controllers/useForm.ts [hunk 7]
```diff
@@ -0,0 +1,349 @@
...
+        return formData;
+      }
+      if (isCheckable(component)) {
+        if (component.checked) {
+          if (inputDelegate && options.inputType === "checkbox") {
+            return inputDelegate.value;
+          }
+          return component.value;
+        }
+        return "";
```
[the remark this answers is not in the document]
Comment (jcfranco) [reply packages/components/src/controllers/useForm.ts]: FYI, `expect(await submitAndGetValue()).toBe(null)` has test-specific logic to handle invalid values by returning `null`. This should be updated to reject instead (in a follow-up PR).

**Review by jcfranco — APPROVED** [review]
